CREATE TABLE "chore-champ_admin_account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chore-champ_admin_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(256) NOT NULL,
	"password_hash" varchar(512) NOT NULL,
	"household_id" integer NOT NULL,
	"member_id" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "chore-champ_admin_account_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "chore-champ_chore_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chore-champ_chore_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chore_id" integer NOT NULL,
	"member_id" integer NOT NULL,
	"points_earned" integer NOT NULL,
	"logged_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chore-champ_chore" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chore-champ_chore_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"icon_name" varchar(64) NOT NULL,
	"icon_style" varchar(16) DEFAULT 'empty' NOT NULL,
	"points" integer NOT NULL,
	"household_id" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chore-champ_household" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chore-champ_household_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chore-champ_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chore-champ_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"avatar_url" varchar(512),
	"household_id" integer NOT NULL,
	"is_admin" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "chore-champ_admin_account" ADD CONSTRAINT "chore-champ_admin_account_household_id_chore-champ_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."chore-champ_household"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore-champ_admin_account" ADD CONSTRAINT "chore-champ_admin_account_member_id_chore-champ_member_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."chore-champ_member"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore-champ_chore_log" ADD CONSTRAINT "chore-champ_chore_log_chore_id_chore-champ_chore_id_fk" FOREIGN KEY ("chore_id") REFERENCES "public"."chore-champ_chore"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore-champ_chore_log" ADD CONSTRAINT "chore-champ_chore_log_member_id_chore-champ_member_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."chore-champ_member"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore-champ_chore" ADD CONSTRAINT "chore-champ_chore_household_id_chore-champ_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."chore-champ_household"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chore-champ_member" ADD CONSTRAINT "chore-champ_member_household_id_chore-champ_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."chore-champ_household"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "admin_email_idx" ON "chore-champ_admin_account" USING btree ("email");--> statement-breakpoint
CREATE INDEX "chore_log_member_idx" ON "chore-champ_chore_log" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "chore_log_chore_idx" ON "chore-champ_chore_log" USING btree ("chore_id");--> statement-breakpoint
CREATE INDEX "chore_log_logged_at_idx" ON "chore-champ_chore_log" USING btree ("logged_at");--> statement-breakpoint
CREATE INDEX "chore_household_idx" ON "chore-champ_chore" USING btree ("household_id");--> statement-breakpoint
CREATE INDEX "member_household_idx" ON "chore-champ_member" USING btree ("household_id");